services:
  - type: web
    plan: free
    name: learning_log
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn learning_log.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: my_project.settings