services:
  - type: web
    plan: free
    name: learning_log
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn learning_log.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: learning_log.settings